namespace JxlNet;

public enum JxlExtraChannelType
{
    JXL_CHANNEL_ALPHA,
    JXL_CHANNEL_DEPTH,
    JXL_CHANNEL_SPOT_COLOR,
    JXL_CHANNEL_SELECTION_MASK,
    JXL_CHANNEL_BLACK,
    JXL_CHANNEL_CFA,
    JXL_CHANNEL_THERMAL,
    JXL_CHANNEL_RESERVED0,
    JXL_CHANNEL_RESERVED1,
    JXL_CHANNEL_RESERVED2,
    JXL_CHANNEL_RESERVED3,
    JXL_CHANNEL_RESERVED4,
    JXL_CHANNEL_RESERVED5,
    JXL_CHANNEL_RESERVED6,
    JXL_CHANNEL_RESERVED7,
    JXL_CHANNEL_UNKNOWN,
    JXL_CHANNEL_OPTIONAL,
}
