<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <Title>JxlNet</Title>
    <Version>0.12.0.0</Version>
    <Authors>Guerra24</Authors>
    <Description>Native bindings for libjxl</Description>
    <PackageId>JxlNet</PackageId>
    <PackageProjectUrl>https://github.com/Guerra24/JxlNet</PackageProjectUrl>
    <PackageTags>jpegxl;jpeg xl;libjxl;jxl;decoder;encoder</PackageTags>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Guerra24/JxlNet</RepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="runtimes/win-x64/native/brotlicommon.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="runtimes/win-x64/native/brotlidec.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="runtimes/win-x64/native/brotlienc.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="runtimes/win-x64/native/jxl.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="runtimes/win-x64/native/jxl_cms.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="runtimes/win-x64/native/jxl_threads.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="runtimes/win-arm64/native/brotlicommon.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
    <None Include="runtimes/win-arm64/native/brotlidec.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
    <None Include="runtimes/win-arm64/native/brotlienc.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
    <None Include="runtimes/win-arm64/native/jxl.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
    <None Include="runtimes/win-arm64/native/jxl_cms.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
    <None Include="runtimes/win-arm64/native/jxl_threads.dll" Pack="true" PackagePath="runtimes/win-arm64/native/" />
  </ItemGroup>

</Project>
