namespace JxlNet;

public enum JxlRenderingIntent
{
    JXL_RENDERING_INTENT_PERCEPTUAL = 0,
    JXL_RENDERING_INTENT_RELATIVE,
    JXL_RENDERING_INTENT_SATURATION,
    JXL_RENDERING_INTENT_ABSOLUTE,
}
