namespace JxlNet;

public enum JxlTransferFunction
{
    JXL_TRANSFER_FUNCTION_709 = 1,
    JXL_TRANSFER_FUNCTION_UNKNOWN = 2,
    JXL_TRANSFER_FUNCTION_LINEAR = 8,
    JXL_TRANSFER_FUNCTION_SRGB = 13,
    JXL_TRANSFER_FUNCTION_PQ = 16,
    JXL_TRANSFER_FUNCTION_DCI = 17,
    JXL_TRANSFER_FUNCTION_HLG = 18,
    JXL_TRANSFER_FUNCTION_GAMMA = 65535,
}
